# Generated by Django 4.2.7 on 2023-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
    ]
